# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_chs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(419, 545)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(419, 545))
        Dialog.setMaximumSize(QtCore.QSize(419, 545))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Dialog.setFont(font)
        self.length = QtWidgets.QLineEdit(Dialog)
        self.length.setGeometry(QtCore.QRect(30, 150, 371, 21))
        self.length.setObjectName("length")
        self.copy = QtWidgets.QPushButton(Dialog)
        self.copy.setGeometry(QtCore.QRect(30, 500, 371, 24))
        self.copy.setObjectName("copy")
        self.path = QtWidgets.QLineEdit(Dialog)
        self.path.setGeometry(QtCore.QRect(30, 70, 371, 21))
        self.path.setObjectName("path")
        self.guide2 = QtWidgets.QLabel(Dialog)
        self.guide2.setGeometry(QtCore.QRect(30, 110, 331, 31))
        self.guide2.setWordWrap(True)
        self.guide2.setObjectName("guide2")
        self.generateChart = QtWidgets.QPushButton(Dialog)
        self.generateChart.setGeometry(QtCore.QRect(30, 200, 371, 26))
        self.generateChart.setObjectName("generateChart")
        self.guide1 = QtWidgets.QLabel(Dialog)
        self.guide1.setGeometry(QtCore.QRect(30, 40, 361, 21))
        self.guide1.setWordWrap(True)
        self.guide1.setObjectName("guide1")
        self.guide3 = QtWidgets.QLabel(Dialog)
        self.guide3.setGeometry(QtCore.QRect(30, 260, 91, 16))
        self.guide3.setObjectName("guide3")
        self.chartSource = QtWidgets.QTextBrowser(Dialog)
        self.chartSource.setGeometry(QtCore.QRect(30, 281, 371, 201))
        self.chartSource.setObjectName("chartSource")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(30, 240, 251, 16))
        self.name.setText("")
        self.name.setObjectName("name")

        self.retranslateUi(Dialog)
        self.generateChart.clicked.connect(lambda: Dialog.get_chart(self.path.text(), self.length.text()))
        self.copy.clicked.connect(lambda: Dialog.to_clipboard(self.chartSource.toPlainText()))
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ease Out铺面转换器"))
        self.length.setText(_translate("Dialog", "SONG_LENGTH"))
        self.copy.setText(_translate("Dialog", "复制到剪贴板"))
        self.path.setText(_translate("Dialog", "PATH_TO_CHART_FILE"))
        self.guide2.setText(_translate("Dialog", "malody编辑器中显示的歌曲长度"))
        self.generateChart.setText(_translate("Dialog", "生成谱面"))
        self.guide1.setText(_translate("Dialog", "谱面文件(.mc 或 .json) 路径:"))
        self.guide3.setText(_translate("Dialog", "谱面源代码："))
        self.chartSource.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
